### ISSUE TITLE
Input data type of cytotrace2

### ISSUE THREAD

**Issue by LiuCanidk** [digitalcytometry/cytotrace2#11]
Hi, thanks for this convinient tool!

I notice that the input type can be the "counts" slot or "data" slot. What kind of type does the development team recommend the user to input? And what is the difference between inputting the raw counts and the log-normalized data?

What's more, is there any other preprocessing step needed before input into the cytotrace2? e.g., filtering low quality cells based on min.cell, min.feature, percentage of mitochondrial genes, doublets, etc.

**Comment by savagyan00** [comment]
Hi and thank you for using CytoTRACE 2!

Regarding your question about the type of input data, CytoTRACE 2 is designed to work with gene ranks, so the normalization method, as long as it maintains the gene rankings, should not influence the results. For more details, please refer to item 3 in our [FAQ section](https://github.com/digitalcytometry/cytotrace2?tab=readme-ov-file#frequently-asked-questions).

As for the preprocessing steps, we recommend filtering out low-quality cells following the standard filtering protocols you would otherwise use in your single-cell analysis.

If you have any further questions, please do not hesitate to reach out.

**Comment by LiuCanidk** [comment]
Thank you for your detailed reply!
