### ISSUE TITLE
Understanding the result of CytoTRACE2 in lung cancer malignant cells

### ISSUE THREAD

**Issue by WuRAFY** [digitalcytometry/cytotrace2#28]
Hi, thanks for the great tool, but I am a little confused about the result.

I apply CytoTRACE2 to lung cancer malignant cells and its origin cells and expecting a dedifferentiation process from orgin cell to malignant cell. Here I clustered cells into three groups: Precursor(including origin cells and some origin like malignant cells), Invading and Proliferating(high cell cycle related gene expression) by transcriptome profile. Proliferating cluster have the highest number of genes detected but also is the most differentiated cluster. According to the 2020 cytoTRACE article, from my perspective, proliferating cluster might be the less differentitated cell cluster? but cytoTRACE2 inferred it to be most differentiated cluster.

Could you please help? Much thanks
F.Y

![Rplot](https://github.com/user-attachments/assets/7b0ca8fa-1e9b-4b7d-a7cd-89c0fbb6c743)
![Rplot01](https://github.com/user-attachments/assets/7eb4dc36-a52e-439d-b1b7-c01d2f147b6f)
![Rplot02](https://github.com/user-attachments/assets/bb5e2911-4bb2-4c6a-b26c-594a0e461f33)
![Rplot03](https://github.com/user-attachments/assets/827894f0-f9f2-4c05-805d-cdf452ddeb8e)

**Comment by savagyan00** [comment]
Hello, thank you for reaching out and for using CytoTRACE2.

Based on your description, it seems there’s a bit of confusion regarding the differentiation status of the proliferating cluster. 
CytoTRACE 2 predicts the developmental potential of cells by analyzing gene set enrichment of specific potency-associated gene sets within single-cell RNA-seq data. The tool's inference that the proliferating cluster is the most differentiated might initially seem counterintuitive if expecting these cells to exhibit higher plasticity or ‘stemness’. However, it’s crucial to consider that proliferative capacity doesn’t always correlate with a less differentiated state. For example, proliferating T cells are considered differentiated, because they do not have the potential to differentiate into other cell types. So the CytoTRACE 2 predictions for your proliferating group aren’t considered necessarily wrong in this case.

Moreover, the precursor cluster, which includes origin cells, might naturally resemble a less differentiated state in its normal counterpart, compared to clusters engaged in active proliferation. This aligns with the general observation that the origin or precursor cells typically retain a higher degree of developmental potential, while the “invading” cluster, positioned between the precursor and proliferating clusters, likely represents a transitional state in terms of differentiation.

Let us know if you need further clarification or additional details!
