### ISSUE TITLE
Integration and plotting of genes up and down regulated

### ISSUE THREAD

**Issue by sylestiel** [digitalcytometry/cytotrace2#31]
Hi @ savagyan00 @pptnz,
 
 In order to run cytotrace 2 on multiple datasets how would we proceed using R?  Do we first integrate them in Seurat and load Seurat obj@data or do we load each of the Seurat obj@ counts for each dataset we are  planning on integrating?

More over is there a way to plot the genes associated with cytotrace?

Thank you!

**Comment by savagyan00** [comment]
Hello and thanks for using CytoTRACE 2,

When running our tool on multiple datasets, it's recommended to process _each dataset separately rather than integrating_ them. This approach prevents potential batch effects from impacting the analysis, as CytoTRACE 2 scores for each cell, while unaffected by the broader dataset in their initial predicted value, use information from other cells within the dataset in the post-processing refinement of the scores.

Regarding your question about plotting genes associated with CytoTRACE 2 scores, while direct functionality for this isn't currently provided by the package, you can use the following R code (using the library **ccaPP**) to identify genes correlated with CytoTRACE 2 scores:

```
library(ccaPP)
# Assuming 'gene_expression_data' is your matrix of genes (rows) by samples (columns)
# and 'cytotrace2_score' is the vector of CytoTRACE 2 scores

# Calculate Pearson correlation between each gene and the CytoTRACE 2 scores
ct2genes <- sapply(1:nrow(gene_expression_data),
                     function(x) ccaPP::corPearson(gene_expression_data[x,], cytotrace2_score))
names(ct2genes) <- rownames(gene_expression_data)

# Sort by decreasing order of correlation
ct2_gene_correlations <- sort(ct2genes, decreasing = TRUE)
```
This code will provide a list of genes ordered by their correlation to the inferred CytoTRACE 2 scores.

Feel free to reach out if you need further assistance!

**Comment by sylestiel** [comment]
@savagyan00 

Thank you!!!

**Comment by sylestiel** [comment]
Hi@savagyan00

Need some clarification on the following:
1) Without an integrated dataset how can I compare a given subset of cells or a cluster across multiple datasets using cytotrace2?
2) Is there a script to run iCytotrace in cytotrace2 or does the script from CytoTRACE apply here as well?
3) Do the codes within the R subfolder represent under the hood functionality of the script outlined on the first page?
Thanks!

**Comment by savagyan00** [comment]
Hi @sylestiel,

> 1. Without an integrated dataset how can I compare a given subset of cells or a cluster across multiple datasets using cytotrace2?

All CytoTRACE 2 outputs, except for CytoTRACE2_Relative, are calibrated to be comparable across datasets without further adjustment, provided the predictions are in absolute (not relative) space. Therefore, no integration is recommended over the predictions either. As for CytoTRACE2_Relative, it should not be compared across different runs, as it is based on the ranking and scaling of CytoTRACE2_Scores within the context of the specific input dataset.

>2. Is there a script to run iCytotrace in cytotrace2 or does the script from CytoTRACE apply here as well?

There isn't an iCytoTRACE implementation for CytoTRACE 2, as we don't require any integration and recommend running each dataset separately. If you'd still like to see results on the integrated assay, you can perform integration beforehand, and then pass the integrated expression values for prediction to CytoTRACE 2. It's important to note that integration methods like Harmony and fastMNN do not alter expression data directly; instead, they adjust the lower-dimensional embeddings of cells used for clustering and visualization.

>3. Do the codes within the R subfolder represent under the hood functionality of the script outlined on the first page?

Yes. The prediction algorithm performs as described in the "Under the hood" section, using a pre-trained set of weights for the described calculations.

**Comment by sylestiel** [comment]
Thank you@savagyan00
