### ISSUE TITLE
An upside-down output plot

### ISSUE THREAD

**Issue by kangpury** [digitalcytometry/cytotrace2#37]
Hello, there is a minor issue with the output from CytoTRACE2. 
**The problem is that the clustering appears upside down.**

![outputs](https://github.com/user-attachments/assets/fd1ac053-3182-4d38-bce2-feda84031f34)

The code I entered is as follows.
```
cytotrace2_result <- cytotrace2(msann, is_seurat = T, slot_type = "counts", species = "human", max_pcs = 42)
plots <- plotData(cytotrace2_result, is_seurat = T, pc_dims = 42) 
plots
```

- My msann data is a Seurat object and consists of human data.
- pc_dims = 42 is the number of PCs I arbitrarily set for clustering.

I will list the methods I used to address this issue.

1)
```
cytotrace2_result <- cytotrace2(msann, is_seurat = T, slot_type = "data", species = "human", max_pcs = 42)
plots <- plotData(cytotrace2_result, is_seurat = T, pc_dims = 42)
plots
```
2)
```
cytotrace2_result <- cytotrace2(msann, is_seurat = T, slot_type = "counts", species = "human", max_pcs = 42)
plots <- plotData(cytotrace2_result, is_seurat = T, pc_dims = 42) 
emb_1 <- msann@reductions$pca@cell.embeddings[,1]
emb_2 <- msann@reductions$pca@cell.embeddings[,2]  
plots[["CytoTRACE2_UMAP"]][[1]][["data"]]["UMAP_1"] <- emb_1
plots[["CytoTRACE2_UMAP"]][[1]][["data"]]["UMAP_2"] <- emb_2
plots[["CytoTRACE2_UMAP"]]
```
3)
```
cytotrace2_result <- cytotrace2(msann, is_seurat = T, slot_type = "counts", species = "human", max_pcs = 42)
plots <- plotData(cytotrace2_result, is_seurat = T, pc_dims = 42) 
emb_1 <- msann@reductions$umap@cell.embeddings[,1]
emb_2 <- msann@reductions$umap@cell.embeddings[,2]  
plots[["CytoTRACE2_UMAP"]][[1]][["data"]]["UMAP_1"] <- emb_1
plots[["CytoTRACE2_UMAP"]][[1]][["data"]]["UMAP_2"] <- emb_2
plots[["CytoTRACE2_UMAP"]]
```

How can I create a plot from the CytoTRACE2 output that is not upside down?

Thank you.

**Comment by savagyan00** [comment]
Hello and thank you for reaching out about CytoTRACE 2!

When you use the plotData function, it internally generates a new UMAP using the RunUMAP function with its default seed of 42 and the dimensions set by the pc_dims input argument. Is the first UMAP you shared generated with seed.use = 42 and dims = 1:42? 
Also, are these results generated in the exact same environment (same computer, same OS, same session)? It's important to note that even with the same seed and number of PCs, the exact location of points on a UMAP plot can vary between different computers and operating systems. This variation is due to the inherent randomization in the UMAP algorithm and how different systems manage it.

I'm glad to see that you have achieved a solution by manually changing the embeddings of the CytoTRACE 2 UMAPs to be exactly the same as your initial Seurat object.

Please let us know if you need further assistance with this matter!
