### ISSUE TITLE
Error in var(x) : is.atomic(y) is not TRUE

### ISSUE THREAD

**Issue by xiaoli-gg** [digitalcytometry/cytotrace2#40]
My code is below:
```
> cytotrace2_result_sce <- cytotrace2(
+   sce,                   # 输入的 Seurat 对象或 SingleCellExperiment 对象
+   is_seurat = TRUE,      # 是否为 Seurat 对象
+   slot_type = "counts",  # 数据类型（counts, logcounts 等）
+   species = 'human',     # 物种选择
+   seed = 1234            # 设置随机种子，保证结果可重复
+ )

cytotrace2: Started loading data
Dataset contains 27284 genes and 47920 cells.
cytotrace2: Running on 5 subsample(s) approximately of length 10000
cytotrace2: Started running on subsample(s). This will take a few minutes.
cytotrace2: Started preprocessing.
14097 input genes mapped to model genes.
cytotrace2: Started prediction.
This section will run using  5 / 20 core(s).
Error in var(x) : is.atomic(y) is not TRUE
```
I don't know how to solve this issue. I will be grateful if you told me the method solving this error!

**Comment by savagyan00** [comment]
Hi and thank you for using CytoTRACE 2, 

This issue stems from a conflict between specific versions of some of the package dependencies. It would be helpful to install the package and all its dependencies in a clean environment. Ideally, use the package versions provided [here](https://github.com/digitalcytometry/cytotrace2/blob/main/environment_R.yml). Alternatively, you can share your session info so that we can make more informed suggestions on how to solve the problem.

We appreciate your collaboration!

**Comment by xiaoli-gg** [comment]
Thanks for your reply! I can run this code normally, today.

**Comment by savagyan00** [comment]
Glad to hear! Please don't hesitate to contact us with any questions in the future.
