### ISSUE TITLE
undefined columns selected

### ISSUE THREAD

**Issue by victorwang123** [digitalcytometry/cytotrace2#43]
Hi，great to see the new version! 
I followed the tutorial to do it, but when using plotData, the following error occurred. Do you know what's going on?
`library(CytoTRACE2)`
`expression_data <- seurat_obj@assays$RNA@counts`
`cytotrace2_result <- cytotrace2(expression_data)`
`annotation <- seurat_obj$seurat_clusters`
`plots <- plotData(cytotrace2_result = cytotrace2_result, annotation = annotation,expression_data = expression_data)`

-Error in `[.data.frame`(annotation, "Phenotype") : 
-undefined columns selected

**Comment by mrBanana0817** [comment]
same error, try this instead
`annotation <- seurat_obj@meta.data['seurat_clusters']`
Because the input 'annotation' is required as data.frame not vector according to their code from 'plotting.R':
`names(annotation)[1] <- "Phenotype"` 
`annotation <- merge(prediction, annotation, by = "row.names", all.x = TRUE)` 
`rownames(annotation) <- annotation$Row.names` 
`annotation$Row.names <- NULL`

**Comment by savagyan00** [comment]
Thank you for your suggestion @mrBanana0817, that indeed seems to be the issue here. 
@victorwang123 please let us know if this suggestion worked for you. If you need further assistance we'd be glad to help!

**Comment by victorwang123** [comment]
Thanks for your reply. Yes, it works well!
