### ISSUE TITLE
Error:  'names' attribute [8916] must be the same length as the vector [9]

### ISSUE THREAD

**Issue by apal6** [digitalcytometry/cytotrace2#8]
Hi,

I got cytotrace2 working on one of the dataset but when I tried it on a new dataset, it gives an error that I am not sure about. Could you help? 

`cytotrace2_result <- cytotrace2(expression_data)
cytotrace2: Started loading data
Dataset contains 32197 genes and 35664 cells.
cytotrace2: Running on 4 subsample(s) approximately of length 10000
cytotrace2: Started running on subsample(s). This will take a few minutes.
cytotrace2: Started preprocessing.
The function expects an input of type 'data.frame' or 'data.table'.
Attempting to convert the provided input to the required format.
11 input genes mapped to model genes.
cytotrace2: Started prediction.
This section will run using  5 / 10 core(s).
cytotrace2: Started postprocessing.
cytotrace2: Running with fast mode (subsamples are processed in parallel)
This section will run on 9 sub-sample(s) of approximately 991 cells each using 9 / 10 core(s).
Error in names(cytotrace) <- unlist(sample_names) : 
  'names' attribute [8916] must be the same length as the vector [9]
In addition: Warning messages:
1: In cytotrace2(expression_data) :
  Species is most likely human. Please revise the 'species' input to the function.
2: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 2.1 GiB
3: In preprocessData(dt, species) :
  The number of input genes mapped to the model is too low. Please verify the input species is correct.
In case of a correct species input, be advised that model performance might be compromised due to gene space differences.
4: In parallel::mclapply(subsamples, mc.cores = min(chunk_number, ncores),  :
  all scheduled cores encountered errors in user code`

Thank you!

**Comment by savagyan00** [comment]
Hi and thank you for reaching out!

Based on the error and warning messages from this run, the number of input genes mapped to the model is too low. Please verify the input species is correct--if species should be ‘human’, you will need to pass species = "human" within your function call. If the species input is correct and your input dataset has very little overlap with our model’s features, please be advised that model performance might be compromised due to gene space differences.

Please let us know if we can help investigate this further!

**Comment by savagyan00** [comment]
Hi,

As per our recent email exchanges, it appears that this specific issue has been successfully resolved, as you were able to run the function and generate results. Consequently, I am closing this issue ticket.

Thank you for reaching out to us!
